# Generated by Django 6.0.2 on 2026-02-25 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('angry', 'Angry'), ('excited', 'Excited'), ('tired', 'Tired')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='sleep_hours',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(24.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='stress_level',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
