# Generated by Django 6.0.2 on 2026-02-25 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_alter_moodentry_mood_alter_moodentry_sleep_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='productivity',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
