# Generated by Django 6.0.2 on 2026-02-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0003_moodentry_productivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Neutral', 'Neutral'), ('Sad', 'Sad'), ('Anxious', 'Anxious'), ('Angry', 'Angry'), ('Excited', 'Excited'), ('Tired', 'Tired')], max_length=20),
        ),
    ]
